markdown: kramdown
permalink: /:title.html
url: tanlonghai.github.io
lsi: true
rouge: true
safe: true

# presonal config
title: longhai's Road
feed: tanlonghai.github.io
comments: disqus

author:
  name: longhai
  nickname: sea
  email: tanlonghaicn@gmail.com
  gmail: tanlonghaicn@gmail.com
  site: tanlonghai.github.io

seo: 
  keyword: 
  description: 
